(in-package :redisc)

(defcmd hdel 2 :integer :vary t)
(defcmd hexists 2 :boolean)
(defcmd hget 2 :string)
(defcmd hgetall 1 :list)
(defcmd hincrby 3 :integer)
(defcmd hincrbyfloat 3 :string) ; < var2.6.0
(defcmd hkeys 1 :list)
(defcmd hlen 1 :integer)
(defcmd hmget 2 :string :vary t)
(defcmd hmset 3 :ok :vary t)
(defcmd hset 3 :boolean)
(defcmd hsetnx 3 :boolean)
(defcmd hvals 1 :list)
