(in-package :redisc)

(defcmd sadd 2 :integer :vary t)
(defcmd scard 1 :integer)
(defcmd sdiff 1 :list :vary t)
(defcmd sdiffstore 2 :integer :vary t)
(defcmd sinter 1 :list :vary t)
(defcmd sinterstore 2 :integer :vary t)
(defcmd sismember 2 :boolean)
(defcmd smembers 1 :list)
(defcmd smove 3 :boolean)
(defcmd spop 1 :string)
(defcmd srandmember 1 :string)
(defcmd srem 2 :integer :vary t)
(defcmd sunion 1 :list :vary t)
(defcmd sunionstore 2 :integer :vary t)
