(in-package :redisc)

(defcmd append 2 :integer)
(defcmd decr 1 :integer)
(defcmd decrby 2 :integer)
(defcmd get 1 :string)
(defcmd getbit 2 :integer)
(defcmd getrange 3 :string)
(defcmd getset 2 :string)
(defcmd incr 1 :integer)
(defcmd incrby 2 :integer)
(defcmd incrbyfloat 2 :string)  ; < ver2.6.0
(defcmd mget 1 :list :vary t)
(defcmd mset 2 :ok :vary t)
(defcmd msetnx 2 :boolean :vary t)
(defcmd psetex 3 :ok) ; < ver2.6.0
(defcmd set 2 :ok)
(defcmd setbit 3 :integer)
(defcmd setex 3 :ok)
(defcmd setnx 2 :boolean)
(defcmd setrange 3 :integer)
(defcmd strlen 1 :integer)
