(in-package :redisc)

(defcmd blpop 2 :list :vary t)
(defcmd brpop 2 :list :vary t)
(defcmd brpoplpush 3 :string)
(defcmd lindex 2 :string)
(defcmd linsert 4 :integer)
(defcmd llen 1 :integer)
(defcmd lpop 1 :string)
(defcmd lpush 2 :integer :vary t)
(defcmd lpushx 2 :integer)
(defcmd lrange 3 :list)
(defcmd lrem 3 :integer)
(defcmd lset 3 :ok)
(defcmd ltrim 3 :ok)
(defcmd rpop 1 :string)
(defcmd rpoplpush 2 :string)
(defcmd rpush 2 :integer :vary t)
(defcmd rpushx 2 :integer)
