(in-package :redisc)

(defcmd bgrewriteaof 0 :status)
(defcmd bgsave 0 :status)
(defcmd config-get 1 :status)
(defcmd config-resetstat 0 :ok)
(defcmd config-set 2 :status)
(defcmd dbsize 0 :integer)
(defcmd debug-object 1 :status)
(defcmd debug-segfault 0 :status)
(defcmd flushall 0 :ok)
(defcmd flushdb 0 :ok)
(defcmd info 0 :string)
(defcmd lastsave 0 :integer)
(defcmd save 0 :status)
(defcmd shutdown 0 :status :vary t) ; XXX: (shutdown 'nosave)とかがエラーになる？(ver2.4.0)
(defcmd slaveof 2 :status)
(defcmd slowlog 1 :object :vary t)
(defcmd sync 0 :status)
(defcmd time 0 :list)  ; >= ver2.6.0
